# Generated by Django 5.2.7 on 2025-10-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReponseQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=100)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "sexe",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Homme", "Homme"),
                            ("Femme", "Femme"),
                            ("Autre", "Autre"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ville", models.CharField(blank=True, max_length=100)),
                ("profession", models.CharField(blank=True, max_length=100)),
                ("connait_med_naturelle", models.BooleanField(default=False)),
                (
                    "utilise_plantes",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Regulierement", "Oui, régulièrement"),
                            ("Parfois", "Oui, parfois"),
                            ("Jamais", "Non, jamais"),
                        ],
                        max_length=50,
                    ),
                ),
                ("types_soins", models.TextField(blank=True)),
                (
                    "frequence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Quotidien", "Quotidiennement"),
                            ("Hebdomadaire", "Hebdomadairement"),
                            ("Mensuel", "Mensuellement"),
                            ("Rarement", "Rarement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lieu_achat", models.TextField(blank=True)),
                (
                    "type_produit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bruts", "Produits bruts"),
                            ("Transformes", "Produits transformés"),
                            ("Peuimporte", "Peu importe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motivations", models.TextField(blank=True)),
                ("criteres_achat", models.TextField(blank=True)),
                ("interet_services", models.TextField(blank=True)),
                (
                    "montant_pret",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("<5000", "< 5 000 FCFA"),
                            ("5000-10000", "5 000 – 10 000 FCFA"),
                            ("10000-20000", "10 000 – 20 000 FCFA"),
                            (">20000", "> 20 000 FCFA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("suggestions", models.TextField(blank=True)),
                ("commentaires", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
