# Generated by Django 5.2.7 on 2025-10-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="sexe",
            field=models.CharField(
                blank=True,
                choices=[("Homme", "Homme"), ("Femme", "Femme"), ("Autre", "Autre")],
                max_length=10,
                null=True,
            ),
        ),
    ]
