# Generated by Django 5.2.7 on 2025-10-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0002_alter_reponsequestionnaire_sexe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="commentaires",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="criteres_achat",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="frequence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Quotidien", "Quotidiennement"),
                    ("Hebdomadaire", "Hebdomadairement"),
                    ("Mensuel", "Mensuellement"),
                    ("Rarement", "Rarement"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="interet_services",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="lieu_achat",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="montant_pret",
            field=models.CharField(
                blank=True,
                choices=[
                    ("<5000", "< 5 000 FCFA"),
                    ("5000-10000", "5 000 – 10 000 FCFA"),
                    ("10000-20000", "10 000 – 20 000 FCFA"),
                    (">20000", "> 20 000 FCFA"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="motivations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="nom",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="profession",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="suggestions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="type_produit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bruts", "Produits bruts"),
                    ("Transformes", "Produits transformés"),
                    ("Peuimporte", "Peu importe"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="types_soins",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="utilise_plantes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Regulierement", "Oui, régulièrement"),
                    ("Parfois", "Oui, parfois"),
                    ("Jamais", "Non, jamais"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reponsequestionnaire",
            name="ville",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
